HotelBomba/urls.py
from django.contrib import admin
from django.template.backends import django
from django.urls import path,include
# imports for media
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('paul/', admin.site.urls),
    path('', include("hotel.urls")),
    path('dashboard/', include('manager.urls')),
    path('register/', include("django.contrib.auth.urls")),
    path('register/', include('register.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from hotel import views


app_name = "blogs"
urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_single/', views.blog_single, name='blog single'),
]

hotel/urls.py
from django.urls import path

from hotel import views
from hotel.views import AddBooking, RoomBookingDetail

app_name = "hotel"
urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('restaurant/', views.restaurant, name='restaurant'),
    path('rooms/', views.rooms, name='rooms'),
    path('blog_single/', views.blog_single, name='blog single'),
    path('rooms_single/', views.rooms_single, name='rooms single'),
    # path('add_booking', views.add_booking, name='add_booking'),
    # path('add_booking', AddBooking.as_view(), name='add_booking'),
    # path('add_booking/<str:category>', RoomBookingDetail.as_view(), name='add_booking'),
    path('add_booking/<str:category>', RoomBookingDetail.as_view(), name='add_booking'),
]

manager/urls.py
from django.urls import path

from . import views



app_name = 'manager'
urlpatterns = [
    path('', views.index, name='dash'),
    path('booking', views.booking, name= 'booking'),
    path('add_booking', views.add_booking, name='add_booking'),
    path('all_booking', views.allbooking, name='all_booking'),
    path('edit_booking', views.edit_booking, name='edit_booking'),
    path('deletebooking<id>', views.deletebooking, name='delete_booking'),

]

register/urls.py
from django.urls import path

from . import views



app_name = 'register'
urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name= 'logout'),
    path('register_user', views.user_register, name='register'),

]

rooms/urls.py
from django.urls import path

from hotel import views


app_name = "rooms"
urlpatterns = [
    path('rooms/', views.rooms, name='rooms'),
    path('rooms_single/', views.rooms_single, name='rooms single'),
]

hotel/models.py
from django.conf import settings
from django.db import models


# Create your models here.

class HeroSection(models.Model):
    text1 = models.CharField(default='', blank=False, max_length=100)
    text2 = models.CharField(default='', blank=False, max_length=100)
    image = models.ImageField(upload_to='hero')


class About(models.Model):
    subheadiing = models.CharField(default='subheading', blank=False, max_length=100)
    h2 = models.CharField(default="heading 2", blank=False, max_length=150)
    text = models.TextField(default='text', blank=False)
    text2 = models.CharField(max_length=100, blank=False)
    background1 = models.ImageField(upload_to='background', default='image')
    background2 = models.ImageField(upload_to='background', default='image')


class Testimony(models.Model):
    name = models.CharField(blank=False, max_length=100)
    position = models.CharField(max_length=50, default="")
    text = models.TextField(blank=False, default='text')
    image = models.ImageField(upload_to="testimonials")


class Menu(models.Model):
    name = models.CharField(blank=False, max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2, )
    text = models.TextField(blank=False, default='description')
    image = models.ImageField(upload_to='restaurant')


    def __int__(self):
        return self.name


class MasterRoom(models.Model):
    name = models.CharField(blank=False, max_length=30)
    price = models.DecimalField(blank=False, decimal_places=2, max_digits=7)
    image = models.ImageField(upload_to='master rooms')

    def __int__(self):
        return self.name
class Blogs(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField(blank=False, default='description')
    image = models.ImageField(upload_to='blogs')

class InstagramImage(models.Model):
    image = models.ImageField(upload_to='instagram images')



class Room(models.Model):
    ROOM_CATEGORIES = (
        ('KIN', 'King Room'),
        ('SUI', 'Suite Room'),
        ('DEL', 'Deluxe Room'),
        ('SUP', 'Superior Room'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField




    def __str__(self):
        return f'{self.number},{self.category} with {self.beds} beds for {self.capacity} adults'

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room =models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'

# models.py
class Book(models.Model):
    check_in = models.DateTimeField(auto_now_add=True)
    check_out = models.DateTimeField(auto_now_add=True)
    room_type = models.CharField(max_length=50)
    guests = models.CharField(max_length=50)
    # date_booked = models.DateTimeField(auto_now_add=True)

hotel/forms.py
from django import forms
from django.forms import ModelForm

from manager.models import Book


class bookingForm(ModelForm):
    class Meta:
        model= Book
        # fields="__all__"
        fields = ('check_in', 'check_out', 'room_type', 'guests')

class AvailabilityForm(forms.Form):
    ROOM_CATEGORIES = (
        ('KIN', 'King Room'),
        ('SUI', 'Suite Room'),
        ('DEL', 'Deluxe Room'),
        ('SUP', 'Superior Room'),
    )
    room_category = forms.ChoiceField(choices=ROOM_CATEGORIES, required=True)
    check_in = forms.DateTimeField(required=True,input_formats=['%Y-%m-%dT%H:%M'])
    check_out = forms.DateTimeField(required=True,input_formats=['%Y-%m-%dT%H:%M'])

blogs/views.py
from django.shortcuts import render

# Create your views here.
def blog(request):
    return render(request, 'blog.html', {'nav': 'blog'})

def blog_single(request):
    return render(request, 'blog-single.html', {'nav': 'blog single'})

hotel/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import FormView
# from rest_framework import request

from hotel.forms import AvailabilityForm
from hotel.models import HeroSection, About, Testimony, MasterRoom, Menu, Blogs, InstagramImage, Booking, Room
from manager.models import Book
from hotel.booking_function.availability import check_availability


# Create your views here.

def master(request):
    # heroslider = HeroSection.objects.all()
    data = HeroSection.objects.all()
    return render(request, 'master.html', {"slides": data})


def index(request):
    about = About.objects.all()[0]
    testimony = Testimony.objects.all()
    Mroom = MasterRoom.objects.all()
    rest = Menu.objects.all()
    blogs = Blogs.objects.all()
    insta = InstagramImage.objects.all()

    room = Room.objects.all()
    room_categories = Room.ROOM_CATEGORIES

    room_list = []
    for room_category, room_display in room_categories:
        # room_url = reverse('hotel:RoomBookingDetail', kwargs={'category': room_category})
        room_url = reverse('hotel:add_booking', kwargs={'category': room_category})
        room_list.append((room_display, room_url))

    context = {
        'nav': 'index',
        "abouts": about,
        "test": testimony,
        "room": Mroom,
        "restaurant": rest,
        "blog": blogs,
        "instagram": insta,
        "room_list": room_list,
    }

    return render(request, "index.html", context)


def about(request):
    about = About.objects.all()[0]
    testimony = Testimony.objects.all()
    return render(request, 'about.html', {"nav": "about", "abouts": about, "testi": testimony})


def blog(request):
    blogs = Blogs.objects.all()
    return render(request, 'blog.html', {'nav': 'blog', 'blog':blogs})


def contact(request):
    return render(request, 'contact.html', {'nav': 'contact'})


def rooms(request):
    Mroom = MasterRoom.objects.all()
    return render(request, 'rooms.html', {'nav': 'rooms', "room": Mroom})


def restaurant(request):
    rest = Menu.objects.all()
    return render(request, 'restaurant.html', {'nav': 'restaurant', "restaurant": rest})


def blog_single(request):
    return render(request, 'restaurant.html', {'nav': 'blog single'})


def rooms_single(request):
    return render(request, 'restaurant.html', {'nav': 'single rooms'})


def add_booking(request):
    if request.method == 'POST':
        check_in = request.POST.get('check_in')
        check_out = request.POST.get('check_out')
        room_type = request.POST.get('room')
        guests = request.POST.get('guest')

        books = Book(check_in=check_in, check_out=check_out, room_type=room_type, guests=guests)
        books.save()
        return redirect('/')

    return redirect('/')



class RoomBookingDetail(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)

        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category, None)
            context = {
                'room_category': room_category,
                'form': form,
            }
            return render(request, 'availability.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are booked!! Try another one')


#
# from django.shortcuts import render
# from django.views import View
# from django.http import JsonResponse
#
# class RoomBookingDetail(View):
#     def post(self, request, *args, **kwargs):
#         category = self.kwargs.get('category', None)
#         room_list = Room.objects.filter(category=category)
#         form = AvailabilityForm(request.POST)
#         data = {}
#
#         if form.is_valid():
#             data = form.cleaned_data
#
#         available_rooms = [room for room in room_list if check_availability(room, data.get('check_in'), data.get('check_out'))]
#
#         if available_rooms:
#             room = available_rooms[0]
#             booking = Booking.objects.create(
#                 user=self.request.user,
#                 room=room,
#                 check_in=data.get('check_in'),
#                 check_out=data.get('check_out')
#             )
#             booking.save()
#             # Modify the response based on your needs (JSON, HTML, etc.)
#             return JsonResponse({'message': 'Booking successful', 'booking_details': {'room_number': room.number, 'check_in': data.get('check_in'), 'check_out': data.get('check_out')}})
#         else:
#             # Modify the response based on your needs (JSON, HTML, etc.)
#             return JsonResponse({'message': 'All rooms of this category are booked. Try another one'})
#




# class RoomBookingDetail(View):
#     def post(self, request, *args, **kwargs):
#         category = self.kwargs.get('category', None)
#         room_list = Room.objects.filter(category=category)
#         form = AvailabilityForm(request.POST)
#         data = {}  # Provide a default value for data
#
#         if form.is_valid():
#             data = form.cleaned_data
#
#         available_rooms = []
#         for room in room_list:
#             if check_availabilty(room, data.get('check_in'), data.get('check_out')):
#                 available_rooms.append(room)
#
#         if len(available_rooms) > 0:
#             room = available_rooms[0]
#             booking = Booking.objects.create(
#                 user=self.request.user,
#                 room=room,
#                 check_in=data.get('check_in'),
#                 check_out=data.get('check_out')
#             )
#             booking.save()
#             return HttpResponse((booking))
#         else:
#             return HttpResponse('All of this category of rooms are booked!! Try another one')


class AddBooking(FormView):
    form_class = AvailabilityForm
    template_name = 'availability.html'

    def form_valid(self, form):
        data = form.cleaned_data
        room_list = Room.objects.filter(category=data['room_category'])  # get a specific category of rooms
        available_rooms = []
        for room in room_list:  # check the available rooms for tha category
            if check_availabilty(room, data['check_in'], data['check_out']):
                available_rooms.append(room)
        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_in']
            )
            booking.save()
            return HttpResponse(booking)
        else:
            return HttpResponse(' Sorry the category of rooms you are looking are currently unavailable')

rooms/views.py
from django.shortcuts import render

from hotel.models import MasterRoom


# Create your views here.
def rooms(request):
    Mroom = MasterRoom.objects.all()
    return render(request, 'rooms.html', {'nav': 'rooms', "room":Mroom})

def rooms_single(request):
    return render(request, 'rooms-single.html', {'nav': 'single rooms'})

hotel/templates/availability.html
{% extends 'master.html' %}
{% load static %}
{% block main %}
{#    <form action="" method="post">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button type="submit" class="btn btn-success">Book Now</button>#}
{#    </form>#}


    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="{% static 'images/room-1.jpg' %}">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:index' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" class="form-control" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" class="form-control" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->


{% endblock %}

hotel/templates/master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bomba Lights</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href = "{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_details.css' %}">



{#      dash#}
{#	<link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicon.png">#}
{#	<link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">#}
{#	<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/fontawesome.min.css">#}
{#	<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/all.min.css">#}
{#	<link rel="stylesheet" href="../static/assets/css/feathericon.min.css">#}
{#	<link rel="stylehseet" href="https://cdn.oesmith.co.uk/morris-0.5.1.css">#}
{#	<link rel="stylesheet" href="../static/assets/plugins/morris/morris.css">#}
{#	<link rel="stylesheet" href="../static/assets/css/style.css">#}

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'hotel:index' %}">Bomba<span>Lights</span></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item {% if nav == 'index' %}active{% endif %}"><a href="{% url 'hotel:index' %}" class="nav-link">Home</a></li>
	          <li class="nav-item {% if nav == 'rooms' %}active{% endif %}"><a href="{% url 'hotel:rooms' %}" class="nav-link">Our Rooms</a></li>
	          <li class="nav-item {% if nav == 'restaurant' %}active{% endif %}"><a href="{% url 'hotel:restaurant' %}" class="nav-link">Restaurant</a></li>
	          <li class="nav-item {% if nav == 'about' %}active{% endif %}"><a href="{% url 'hotel:about' %}" class="nav-link">About Us</a></li>
	          <li class="nav-item {% if nav == 'blog' %}active{% endif %}"><a href="{% url 'hotel:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item {% if nav == 'contact' %}active{% endif %}"><a href="{% url 'hotel:contact' %}" class="nav-link">Contact</a></li>
	          {% if user.is_superuser %}
                <li class="nav-item {% if navbar == 'indexx' %}active{% endif %}"><a href="{% url 'manager:dash' %}" class="nav-link">dashboard</a></li>
                {% endif%}

                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'register:logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'register:register' %}" class="nav-link">Register</a></li>
                    <li class="nav-item"><a href="{% url 'register:login' %}" class="nav-link">Login</a></li>
                {% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>

    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong> You should check in on some of those fields below.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <!-- END nav -->
{#    		<div class="hero">#}
{#	    <section class="home-slider owl-carousel">#}
{#        {% for slide in slides %}#}
{#            <div class="slider-item {% if forloop.counter0 == 0 %} active {% endif %}" style="background-image:url({% static 'images/bg_1.jpg' %});">#}
{#	      	<div class="overlay"></div>#}
{#	        <div class="container">#}
{#	          <div class="row no-gutters slider-text align-items-center justify-content-end">#}
{#	          <div class="col-md-6 ftco-animate">#}
{#	          	<div class="text">#}
{#	          		<h2>{{ slide.text2}}</h2>#}
{#		            <h1 class="mb-3">{{ slide.text1 }}</h1>#}
{#	            </div>#}
{#	          </div>#}
{#	        </div>#}
{#	        </div>#}
{#	      </div>#}
{#        {% endfor %}#}



		<div class="hero">
	    <section class="home-slider owl-carousel">
	      <div class="slider-item" style="background-image:url({% static 'images/bg_1.jpg' %});">
	      	<div class="overlay"></div>
	        <div class="container">
	          <div class="row no-gutters slider-text align-items-center justify-content-end">
	          <div class="col-md-6 ftco-animate">
	          	<div class="text">
	          		<h2>More than a hotel... an experience</h2>
		            <h1 class="mb-3">Hotel for the whole family, all year round.</h1>
	            </div>
	          </div>
	        </div>
	        </div>
	      </div>

	      <div class="slider-item" style="background-image:url({% static 'images/bg_2.jpg' %});">
	      	<div class="overlay"></div>
	        <div class="container">
	          <div class="row no-gutters slider-text align-items-center justify-content-end">
	          <div class="col-md-6 ftco-animate">
	          	<div class="text">
	          		<h2>Bomba Lights Hotel &amp; Resort</h2>
		            <h1 class="mb-3">It feels like staying in your own home.</h1>
	            </div>
	          </div>
	        </div>
	        </div>
	      </div>
	    </section>
	  </div>




{% block main %}

{% endblock %}


    <footer class="ftco-footer ftco-section img" style="background-image: url({% static 'images/bg_4.jpg' %});">
    	<div class="overlay"></div>
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Bomba Lights</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Useful Links</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'hotel:blog' %}" class="py-2 d-block">Blog</a></li>
                <li><a href="{% url 'hotel:rooms' %}" class="py-2 d-block">Rooms</a></li>
                <li><a href="#" class="py-2 d-block">Amenities</a></li>
                <li><a href="#" class="py-2 d-block">Gift Card</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Privacy</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Career</a></li>
                <li><a href="{% url 'hotel:about' %}" class="py-2 d-block">About Us</a></li>
                <li><a href="{% url 'hotel:contact' %}" class="py-2 d-block">Contact Us</a></li>
                <li><a href="#" class="py-2 d-block">Services</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved<i class="icon-heart color-danger" aria-hidden="true"></i><p>GovernorPaul</p>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="../static/js/jquery.min.js"></script>
  <script src="../static/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="../static/js/popper.min.js"></script>
  <script src="../static/js/bootstrap.min.js"></script>
  <script src="../static/js/jquery.easing.1.3.js"></script>
  <script src="../static/js/jquery.waypoints.min.js"></script>
  <script src="../static/js/jquery.stellar.min.js"></script>
  <script src="../static/js/owl.carousel.min.js"></script>
  <script src="../static/js/jquery.magnific-popup.min.js"></script>
  <script src="../static/js/aos.js"></script>
  <script src="../static/js/jquery.animateNumber.min.js"></script>
  <script src="../static/js/bootstrap-datepicker.js"></script>
  <script src="../static/js/scrollax.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="../static/js/google-map.js"></script>
  <script src="../static/js/main.js"></script>


</body>
</html>