HotelBomba/urls.py
from django.contrib import admin
from django.template.backends import django
from django.urls import path,include
# imports for media
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('paul/', admin.site.urls),
    path('', include("hotel.urls")),
    path('dashboard/', include('manager.urls')),
    path('register/', include("django.contrib.auth.urls")),
    path('register/', include('register.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from hotel import views


app_name = "blogs"
urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog_single/', views.blog_single, name='blog single'),
]

hotel/urls.py
from django.urls import path

from hotel import views
from hotel.views import AddBooking, RoomBookingDetail

app_name = "hotel"
urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('restaurant/', views.restaurant, name='restaurant'),
    path('rooms/', views.rooms, name='rooms'),
    path('blog_single/', views.blog_single, name='blog single'),
    path('rooms_single/', views.rooms_single, name='rooms single'),
    # path('add_booking', views.add_booking, name='add_booking'),
    # path('add_booking', AddBooking.as_view(), name='add_booking'),
    # path('add_booking/<str:category>', RoomBookingDetail.as_view(), name='add_booking'),
    path('add_booking/<str:category>', RoomBookingDetail.as_view(), name='add_booking'),
]

manager/urls.py
from django.urls import path

from . import views



app_name = 'manager'
urlpatterns = [
    path('', views.index, name='dash'),
    path('booking', views.booking, name= 'booking'),
    path('add_booking', views.add_booking, name='add_booking'),
    path('all_booking', views.allbooking, name='all_booking'),
    path('edit_booking', views.edit_booking, name='edit_booking'),
    path('deletebooking<id>', views.deletebooking, name='delete_booking'),

]

manager/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    check_in = models.DateTimeField(null=False,default='')
    check_out = models.DateTimeField(null=False, default='')
    room_type = models.CharField(max_length=50)
    guests = models.CharField(max_length=50)

class RoomCategory(models.Model):
    category = models.CharField(max_length=50)
    rate = models.FloatField()

    def __str__(self):
        return self.category


class Room(models.Model):
    number = models.IntegerField()
    beds = models.IntegerField()
    capacity = models.IntegerField()
    category = models.ForeignKey(
        RoomCategory, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.number}. Beds = {self.beds} People = {self.capacity}'

blogs/views.py
from django.shortcuts import render

# Create your views here.
def blog(request):
    return render(request, 'blog.html', {'nav': 'blog'})

def blog_single(request):
    return render(request, 'blog-single.html', {'nav': 'blog single'})

manager/views.py
from django.shortcuts import render

from hotel.models import Booking


# Create your views here.

def index(request):
    bookings = Booking.objects.all()
    context={
        'navbar': 'indexx',
        "books":bookings,
    }
    return render(request, 'indexx.html', context)


def allbooking(request):
    bookings= Booking.objects.all()
    return render(request, 'all-booking.html', {"books":bookings})


def booking(request):
    bookings= Booking.objects.all()
    return render(request, 'all-booking.html', {"books":bookings})


def add_booking(request):
    return render(request, 'add-booking.html', {})

def edit_booking(request):
    return render(request, 'edit-booking.html', {})


def deletebooking(request, id):
    bookings = Booking.objects.get(id=id)
    bookings.delete()
    return render(request,'indexx.html')

manager/templates/add-booking.html
{% extends 'manage_master.html' %}
{% load static %}

{% block body %}
		<div class="page-wrapper">
			<div class="content container-fluid">
				<div class="page-header">
					<div class="row align-items-center">
						<div class="col">
							<h3 class="page-title mt-5">Add Booking</h3> </div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<form action="/add_booking" method="">
                            {% csrf_token %}
							<div class="row formtype">
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Booking ID</label>#}
{#										<input class="form-control" type="text" value="BKG-0001"> </div>#}
{#								</div>#}
								<div class="col-md-4">
									<div class="form-group">
										<label>Name</label>
										<select class="form-control" id="sel1" name="sellist1">
											<option>Select</option>
											<option>Jennifer Robinson</option>
											<option>Terry Baker</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Room Type</label>
										<select class="form-control" id="sel2" name="sellist1">
											<option>Select</option>
											<option>Single</option>
											<option>Double</option>
											<option>Quad</option>
											<option>King</option>
											<option>Suite</option>
											<option>Villa</option>
										</select>
									</div>
								</div>
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Total Members</label>#}
{#										<select class="form-control" id="sel3" name="sellist1">#}
{#											<option>Select</option>#}
{#											<option>1</option>#}
{#											<option>2</option>#}
{#											<option>3</option>#}
{#											<option>4</option>#}
{#											<option>5</option>#}
{#										</select>#}
{#									</div>#}
{#								</div>#}
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Date</label>#}
{#										<div class="cal-icon">#}
{#											<input type="text" class="form-control datetimepicker"> </div>#}
{#									</div>#}
{#								</div>#}
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Time</label>#}
{#										<div class="time-icon">#}
{#											<input type="text" class="form-control" id="datetimepicker3"> </div>#}
{#									</div>#}
{#								</div>#}
								<div class="col-md-4">
									<div class="form-group">
										<label>Arrival Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Depature Date</label>
										<div class="cal-icon">
											<input type="text" class="form-control datetimepicker"> </div>
									</div>
								</div>
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Email ID</label>#}
{#										<input type="text" class="form-control" id="usr"> </div>#}
{#								</div>#}
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Phone Number</label>#}
{#										<input type="text" class="form-control" id="usr1"> </div>#}
{#								</div>#}
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>File Upload</label>#}
{#										<div class="custom-file mb-3">#}
{#											<input type="file" class="custom-file-input" id="customFile" name="filename">#}
{#											<label class="custom-file-label" for="customFile">Choose file</label>#}
{#										</div>#}
{#									</div>#}
{#								</div>#}
{#								<div class="col-md-4">#}
{#									<div class="form-group">#}
{#										<label>Message</label>#}
{#										<textarea class="form-control" rows="5" id="comment" name="text"></textarea>#}
{#									</div>#}
{#								</div>#}
							</div>
						</form>
					</div>
				</div>
				<button type="button" class="btn btn-primary buttonedit1">Create Booking</button>
			</div>
		</div>

	<script>
	$(function() {
		$('#datetimepicker3').datetimepicker({
			format: 'LT'
		});
	});
	</script>
{% endblock %}

manager/templates/add-room.html
{% extends 'manage_master.html' %}
{% load static %}

{% block body %}

		<div class="page-wrapper">
			<div class="content container-fluid">
				<div class="page-header">
					<div class="row align-items-center">
						<div class="col">
							<h3 class="page-title mt-5">Add Room</h3> </div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<form>
							<div class="row formtype">
								<div class="col-md-4">
									<div class="form-group">
										<label>Room Number</label>
										<input class="form-control" type="text" value="BKG-0001"> </div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Room Type</label>
										<select class="form-control" id="sel1" name="sellist1">
											<option>Select</option>
											<option>Single</option>
											<option>Double</option>
											<option>Quad</option>
											<option>King</option>
											<option>Suite</option>
											<option>Villa</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>AC/NON-AC</label>
										<select class="form-control" id="sel2" name="sellist1">
											<option>Select</option>
											<option>AC</option>
											<option>NON-AC</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Food</label>
										<select class="form-control" id="sel3" name="sellist1">
											<option>Select</option>
											<option>Free Breakfast</option>
											<option>Free Lunch</option>
											<option>Free Dinner</option>
											<option>Free Breakfast & Dinner</option>
											<option>Free Welcome Drink</option>
											<option>No Free Food</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Bed Count</label>
										<select class="form-control" id="sel" name="sellist1">
											<option>Select</option>
											<option>1</option>
											<option>2</option>
											<option>3</option>
											<option>4</option>
											<option>5</option>
											<option>6</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Charges For cancellation</label>
										<select class="form-control" id="sel4" name="sellist1">
											<option>Select</option>
											<option>Free</option>
											<option>5% Before 24Hours</option>
											<option>No Cancellation Allow</option>
										</select>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Rent</label>
										<input type="text" class="form-control" id="usr"> </div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Phone Number</label>
										<input type="text" class="form-control" id="usr1"> </div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>File Upload</label>
										<div class="custom-file mb-3">
											<input type="file" class="custom-file-input" id="customFile" name="filename">
											<label class="custom-file-label" for="customFile">Choose file</label>
										</div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>Message</label>
										<textarea class="form-control" rows="5" id="comment" name="text"></textarea>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
				<button type="button" class="btn btn-primary buttonedit ml-2">Save</button>
				<button type="button" class="btn btn-primary buttonedit">Cancel</button>
			</div>
		</div>

{% endblock %}

manager/templates/error-500.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
<title>Hotel Dashboard Template</title>

<link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicon.png">

<link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">

<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/all.min.css">
<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/fontawesome.min.css">

<link rel="stylesheet" href="../static/assets/css/feathericon.min.css">
<link rel="stylesheet" href="../static/assets/plugins/morris/morris.css">

<link rel="stylesheet" href="../static/assets/css/style.css">

</head>

<body class="error-page">

<div class="main-wrapper">
<div class="error-box">
<h1>500</h1>
<h3 class="h2 mb-3"><i class="fas fa-exclamation-triangle"></i> Oops! Something went wrong</h3>
<p class="h4 font-weight-normal">The page you requested was not found.</p>
<a href="indexx.html" class="btn btn-primary">Back to Home</a>
</div>
</div>


<script src="../static/assets/js/jquery-3.5.1.min.js"></script>

<script src="../static/assets/js/popper.min.js"></script>
<script src="../static/assets/js/bootstrap.min.js"></script>

<script src="../static/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<script src="../static/assets/js/script.js"></script>
</body>
</html>

manager/templates/manage_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Hotel Dashboard Template</title>
	<link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicon.png">
	<link rel="stylesheet" href="../static/assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/fontawesome.min.css">
	<link rel="stylesheet" href="../static/assets/plugins/fontawesome/css/all.min.css">
	<link rel="stylesheet" href="../static/assets/css/feathericon.min.css">
	<link rel="stylehseet" href="https://cdn.oesmith.co.uk/morris-0.5.1.css">
	<link rel="stylesheet" href="../static/assets/plugins/morris/morris.css">
	<link rel="stylesheet" href="../static/assets/css/style.css">
</head>

<body>
	<div class="main-wrapper">
		<div class="header">
			<div class="header-left">
{#                <img src="{% static 'assets/img/hotel_logo.png' %}" width="50" height="70" alt="logo"> #}
				<a href="#" class="logo"> <span class="logoclass">HOTELBOMBA</span> </a>
				<a href="indexx.html" class="logo logo-small"> <img src="../static/assets/img/hotel_logo.png" alt="Logo" width="30" height="30"> </a>
			</div>
			<a href="javascript:void(0);" id="toggle_btn"> <i class="fe fe-text-align-left"></i> </a>
			<a class="mobile_btn" id="mobile_btn"> <i class="fas fa-bars"></i> </a>
			<ul class="nav user-menu">
				<li class="nav-item dropdown noti-dropdown">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <i class="fe fe-bell"></i> <span class="badge badge-pill">3</span> </a>
					<div class="dropdown-menu notifications">
						<div class="topnav-dropdown-header"> <span class="notification-title">Notifications</span> <a href="javascript:void(0)" class="clear-noti"> Clear All </a> </div>
						<div class="noti-content">
							<ul class="notification-list">
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="../static/assets/img/profiles/avatar-02.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
												<p class="noti-time"><span class="notification-time">4 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="../static/assets/img/profiles/avatar-11.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">International Software
													Inc</span> has sent you a invoice in the amount of <span class="noti-title">$218</span></p>
												<p class="noti-time"><span class="notification-time">6 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="../static/assets/img/profiles/avatar-17.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request <span class="noti-title">Apple iPhone
													XR</span></p>
												<p class="noti-time"><span class="notification-time">8 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
								<li class="notification-message">
									<a href="#">
										<div class="media"> <span class="avatar avatar-sm">
											<img class="avatar-img rounded-circle" alt="User Image" src="../static/assets/img/profiles/avatar-13.jpg">
											</span>
											<div class="media-body">
												<p class="noti-details"><span class="noti-title">Mercury Software
												Inc</span> added a new product <span class="noti-title">Apple
												MacBook Pro</span></p>
												<p class="noti-time"><span class="notification-time">12 mins ago</span> </p>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
						<div class="topnav-dropdown-footer"> <a href="#">View all Notifications</a> </div>
					</div>
				</li>
				<li class="nav-item dropdown has-arrow">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <span class="user-img"><img class="rounded-circle" src="../static/assets/img/profiles/avatar-01.jpg" width="31" alt="Soeng Souy"></span> </a>
					<div class="dropdown-menu">
						<div class="user-header">
							<div class="avatar avatar-sm"> <img src="../static/assets/img/profiles/avatar-01.jpg" alt="User Image" class="avatar-img rounded-circle"> </div>
							<div class="user-text">
								<h6>Paul Ng'ang'a</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div> <a class="dropdown-item" href="profile.html">My Profile</a> <a class="dropdown-item" href="settings.html">Account Settings</a> <a class="dropdown-item" href="{% url 'hotel:index' %}">Homepage</a> </div>
				</li>
			</ul>
			<div class="top-nav-search">
				<form>
					<input type="text" class="form-control" placeholder="Search here">
					<button class="btn" type="submit"><i class="fas fa-search"></i></button>
				</form>
			</div>
		</div>
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li class="active"> <a href="{% url 'manager:dash' %}"><i class="fas fa-tachometer-alt"></i> <span>Dashboard</span></a> </li>
						<li class="list-divider"></li>
						<li class="submenu"> <a href="#"><i class="fas fa-suitcase"></i> <span> Booking </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'manager:booking' %}"> All Booking </a></li>
								<li><a href="{% url 'manager:edit_booking' %}"> Edit Booking </a></li>
								<li><a href="{% url 'manager:add_booking' %}"> Add Booking </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Customers </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="all-customer.html"> All customers </a></li>
								<li><a href="edit-customer.html"> Edit Customer </a></li>
								<li><a href="add-customer.html"> Add Customer </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-key"></i> <span> Rooms </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="all-rooms.html">All Rooms </a></li>
								<li><a href="edit-room.html"> Edit Rooms </a></li>
								<li><a href="add-room.html"> Add Rooms </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Staff </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">All Staff </a></li>
								<li><a href="#"> Edit Staff </a></li>
								<li><a href="#"> Add Staff </a></li>
							</ul>
						</li>
						<li> <a href="#"><i class="far fa-money-bill-alt"></i> <span>Pricing</span></a> </li>
						<li class="submenu"> <a href="#"><i class="fas fa-share-alt"></i> <span> Apps </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#"><i class="fas fa-comments"></i><span> Chat </span></a></li>
								<li class="submenu"> <a href="#"><i class="fas fa-video camera"></i> <span> Calls </span> <span class="menu-arrow"></span></a>
									<ul class="submenu_class" style="display: none;">
										<li><a href="#"> Voice Call </a></li>
										<li><a href="#"> Video Call </a></li>
										<li><a href="#"> Incoming Call </a></li>
									</ul>
								</li>
								<li class="submenu"> <a href="#"><i class="fas fa-envelope"></i> <span> Email </span> <span class="menu-arrow"></span></a>
									<ul class="submenu_class" style="display: none;">
										<li><a href="#">Compose Mail </a></li>
										<li><a href="#"> Inbox </a></li>
										<li><a href="#"> Mail Veiw </a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Employees </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Employees List </a></li>
								<li><a href="#">Leaves </a></li>
								<li><a href="#">Holidays </a></li>
								<li><a href="#">Attendance </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="far fa-money-bill-alt"></i> <span> Accounts </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Invoices </a></li>
								<li><a href="#">Payments </a></li>
								<li><a href="#">Expenses </a></li>
								<li><a href="#">Taxes </a></li>
								<li><a href="#">Provident Fund </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-book"></i> <span> Payroll </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Employee Salary </a></li>
								<li><a href="#">Payslip </a></li>
							</ul>
						</li>
						<li> <a href="calendar.html"><i class="fas fa-calendar-alt"></i> <span>Calendar</span></a> </li>
						<li class="submenu"> <a href="#"><i class="fe fe-table"></i> <span> Blog </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="blog.html">Blog </a></li>
								<li><a href="blog-details.html">Blog Veiw </a></li>
								<li><a href="add-blog.html">Add Blog </a></li>
								<li><a href="edit-blog.html">Edit Blog </a></li>
							</ul>
						</li>
						<li> <a href="#"><i class="fas fa-cube"></i> <span>Assests</span></a> </li>
						<li> <a href="#"><i class="far fa-bell"></i> <span>Activities</span></a> </li>
						<li class="submenu"> <a href="#"><i class="fe fe-table"></i> <span> Reports </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Expense Report </a></li>
								<li><a href="#">Invoice Report </a></li>
							</ul>
						</li>
						<li> <a href="#"><i class="fas fa-cog"></i> <span>Settings</span></a> </li>
						<li class="list-divider"></li>
						<li class="menu-title mt-3"> <span>UI ELEMENTS</span> </li>
						<li class="submenu"> <a href="#"><i class="fas fa-laptop"></i> <span> Components </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">UI Kit </a></li>
								<li><a href="#">Typography </a></li>
								<li><a href="#">Tabs </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-edit"></i> <span> Forms </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Basic Input </a></li>
								<li><a href="#">Input Groups </a></li>
								<li><a href="#">Horizontal Form </a></li>
								<li><a href="#">Vertical Form </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-table"></i> <span> Tables </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Basic Table </a></li>
								<li><a href="#">Data Table </a></li>
							</ul>
						</li>
						<li class="list-divider"></li>
						<li class="menu-title mt-3"> <span>EXTRAS</span> </li>
						<li class="submenu"> <a href="#"><i class="fas fa-columns"></i> <span> Pages </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="#">Login </a></li>
								<li><a href="#">Register </a></li>
								<li><a href="#">Forgot Password </a></li>
								<li><a href="#">Change Password </a></li>
								<li><a href="#">Lockscreen </a></li>
								<li><a href="profile.html">Profile </a></li>
								<li><a href="#">Gallery </a></li>
								<li><a href="error-404.html">404 Error </a></li>
								<li><a href="error-500.html">500 Error </a></li>
								<li><a href="#">Blank Page </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-share-alt"></i> <span> Multi Level </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="">Level 1 </a></li>
								<li><a href="">Level 2 </a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>

        {% block body %}

        {% endblock %}
	</div>

	<script src="../static/assets/js/jquery-3.5.1.min.js"></script>
	<script src="../static/assets/js/popper.min.js"></script>
	<script src="../static/assets/js/bootstrap.min.js"></script>
	<script src="../static/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
	<script src="../static/assets/plugins/raphael/raphael.min.js"></script>
	<script src="../static/assets/js/moment.min.js"></script>
	<script src="../static/assets/js/bootstrap-datetimepicker.min.js"></script>
	<script src="../static/assets/js/script.js"></script>
	<script>
	$(function() {
		$('#datetimepicker3').datetimepicker({
			format: 'LT'
		});
	});
	</script>
</body>

</html>